ARG CONFLUENT_VERSION=6.0.0

FROM maven:3.8-jdk-11

FROM confluentinc/cp-kafka-connect:$CONFLUENT_VERSION
ENV CONFLUENT_VERSION $CONFLUENT_VERSION
LABEL version=$CONFLUENT_VERSION

RUN wget https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.9.7.Final/debezium-connector-mysql-1.9.7.Final-plugin.tar.gz
RUN tar xzf debezium-connector-mysql-1.9.7.Final-plugin.tar.gz
RUN cp -R debezium-connector-mysql /usr/share/java

CMD ["/etc/confluent/docker/run"]
